### ISSUE TITLE
pip install: No such file or directory: CHANGELOG.rst

### ISSUE THREAD

**Issue by ynerant** [blueschu/django-htcpcp-tea#1]
When trying to install django-htcpcp-tea from pip, it fails:

```bash
$ pip install django-htcpcp-tea==0.7.0
Collecting django-htcpcp-tea==0.7.0
  Downloading django-htcpcp-tea-0.7.0.tar.gz (27 kB)
    ERROR: Command errored out with exit status 1:
     command: <env>/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2zna_8no/django-htcpcp-tea/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2zna_8no/django-htcpcp-tea/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-38gaa4fk
         cwd: /tmp/pip-install-2zna_8no/django-htcpcp-tea/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2zna_8no/django-htcpcp-tea/setup.py", line 17, in <module>
        with open(os.path.join(BASE_DIR, 'CHANGELOG.rst')) as changes:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-2zna_8no/django-htcpcp-tea/CHANGELOG.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I tried in several different python environment. This fail does not appear in the versions before 0.3.0.

**Comment by blueschu** [comment]
Fixed in v0.8.0 (fde680e)
